parameters:
  - name: serviceConnection
    type: string
  - name: poolName
    type: string
  - name: deployEnvironment
    type: string
  - name: branchName
    type: string
  - name: sharePath
    type: string
  - name: databricks_host
    type: string
  - name: databricks_token
    type: string

jobs:
  - deployment: DeploymentADB
    environment: ${{ parameters.deployEnvironment }}
    displayName: 'Deploy to ${{ parameters.deployEnvironment }}'
    timeoutInMinutes: 30
    pool: ${{ parameters.poolName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Bash@3
              displayName: 'Configure Databricks CLI'
              inputs:
                targetType: 'inline'
                script: |
                  echo "Configure Databricks CLI"
                  echo "host = ${{ parameters.databricks_host }}" > ~/.databrickscfg
                  echo "token = ${{ parameters.databricks_token }}" >> ~/.databrickscfg
                  cat ~/.databrickscfg
                  
            - task: AzureCLI@2
              inputs:
                azureSubscription: ${{ parameters.serviceConnection }}
                scriptType: 'bash'
                useGlobalConfig: true
                scriptLocation: 'inlineScript'
                inlineScript: |                
                  echo "Checking out the ${{ parameters.branchName }} branch in the ${{ parameters.sharePath }} directory"
                  databricks repos update "${{ parameters.sharePath }}" --branch "${{ parameters.branchName }}"